services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - 3020:80/tcp
    environment:
      TZ: Asia/Bangkok
    volumes:
      - ../_protected/wallos/db:/var/www/html/db
      - ../_protected/wallos/logos:/var/www/html/images/uploads/logos
    restart: unless-stopped
