services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    restart: always
    ports:
      - "3030:8080"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    user: "${UID}:${GID}"
    environment:
      WEBUI_AUTH: "false"
      WEBUI_NAME: "Alan"
      ENABLE_COMMUNITY_SHARING: "false"
      #OLLAMA_BASE_URL: "http://127.0.0.1:11434"
    volumes:
      - /home/patrick/github.com/davidsneighbour/dotfiles/modules/containers/_protected/ollama:/root/.ollama
      - /home/patrick/github.com/davidsneighbour/dotfiles/modules/containers/_protected/alan:/app/backend/data
